Gov.GTB.FirmaTalepTakip.Web/Controllers/FirmaController.cs
using System.Web.Mvc;
using System.Linq;
using Gov.GTB.FirmaTalepTakip.Repository.Interface;
using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete;
using Gov.GTB.FirmaTalepTakip.Model.Entities;
using Gov.GTB.FirmaTalepTakip.Model.ViewModel;
using AutoMapper;
using System.Collections.Generic;
using Gov.GTB.FirmaTalepTakip.Web.Helpers;

namespace Gov.GTB.FirmaTalepTakip.Web.Controllers
{
    [Authorize]
    [SessionExpireFilter]
    public class FirmaController : Controller
    {
        private readonly IFirmaRepository _firmaRepository;
        private readonly IGumrukKodRepository _bolgeKodRepository;

        public FirmaController(IFirmaRepository firmaRepository, IGumrukKodRepository bolgeKodRepository)
        {
            this._firmaRepository = firmaRepository;
            this._bolgeKodRepository = bolgeKodRepository;
        }

        public ActionResult Liste()
        {
            var firmalar = _firmaRepository.FirmaListesi();
            return View(firmalar);
        }

        public ActionResult Ekle()
        {
            var firmaViewModel = new FirmaViewModel
            {
                GumrukKodlari = BolgeKodGetir(),
                IsDisabled = false
            };
            return View("Duzenle", firmaViewModel);
        }

        public ActionResult Duzenle(int firmaId)
        {
            var firmaFromDb = _firmaRepository.FirmaGetir(firmaId);
            var firmaViewModel = Mapper.Map<Firma, FirmaViewModel>(firmaFromDb);
            firmaViewModel.GumrukKodlari = BolgeKodGetir();
            firmaViewModel.IsDisabled = true;
            return View(firmaViewModel);
        }

        [HttpPost]
        public ActionResult Duzenle(FirmaViewModel firmaViewModel)
        {
            if (ModelState.IsValid)
            {
                var firma = Mapper.Map<FirmaViewModel, Firma>(firmaViewModel);
                _firmaRepository.FirmaKaydetGuncelle(firma);
                return RedirectToAction("Liste");
            }
            else
            {
                firmaViewModel.GumrukKodlari = BolgeKodGetir();
                if (firmaViewModel.Id > 0)
                {
                    firmaViewModel.IsDisabled = true;
                }
                return View("Duzenle", firmaViewModel);
            }
        }

        public ActionResult Ara(string vergiNo)
        {
            var firmalar = _firmaRepository.FirmaListesi();

            if (string.IsNullOrEmpty(vergiNo))
            {
                ModelState.AddModelError("vergiNo", Resources.VergiNoEmptyErrorMsg);
                return View("Liste", firmalar);
            }

            long vergiNoParam = 0;
            if (!long.TryParse(vergiNo, out vergiNoParam))
            {
                ModelState.AddModelError("vergiNo", Resources.VergiNoFormatErrorMsg);
                return View("Liste", firmalar);
            }

            var filteredFirmalar = firmalar.Where(z => z.VergiNo == vergiNoParam);
            return View("Liste", filteredFirmalar);
        }

        private IEnumerable<GumrukKodViewModel> BolgeKodGetir()
        {
            var bolgeKodlari = _bolgeKodRepository.BolgeKodListesi();
            return Mapper.Map<IEnumerable<GumrukKod>, IEnumerable<GumrukKodViewModel>>(bolgeKodlari);
        }

        public ActionResult Sil(int firmaId)
        {
            _firmaRepository.FirmaSil(firmaId);
            return RedirectToAction("Liste");
        }
    }
}

Gov.GTB.FirmaTalepTakip.Web/Views/Firma/Duzenle.cshtml
@using Gov.GTB.FirmaTalepTakip.Web.Helpers
@using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete;
@model Gov.GTB.FirmaTalepTakip.Model.ViewModel.FirmaViewModel
@{
    ViewBag.Title = "Firma " + ((@Model.IsDisabled) ? "Düzenle" : "Kayıt");
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

@{
    var bolgeKodlari = new List<SelectListItem> { };
    if (Model.GumrukKodlari != null)
    {
        Model.GumrukKodlari.ToList().ForEach(g => bolgeKodlari.Add(
            new SelectListItem()
            {
                Text = g.Adi,
                Value = g.BolgeKodu
            }));
    }
}

@using (Html.BeginForm("Duzenle", "Firma", FormMethod.Post))
{
    @Html.Hidden("FirmaId", Model.Id)
    @Html.Hidden("IsDisabled", Model.IsDisabled)
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-body">
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("VergiNo", ViewData.ModelState)">
                        <label>Vergi No </label>
                        @if (!Model.IsDisabled)
                        {
                            @Html.TextBoxFor(m => m.VergiNo, null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.VergiNo, "", new { @class = "help-block" })
                        }
                        else
                        {
                            @Html.TextBoxFor(m => m.VergiNo, null, new { @class = "form-control", @readonly = true })
                        }
                    </div>
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("Adi", ViewData.ModelState)">
                        <label>Adı </label>
                        @if (!Model.IsDisabled)
                        {
                            @Html.TextBoxFor(m => m.Adi, null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Adi, "", new { @class = "help-block" })
                        }
                        else
                        {
                            @Html.TextBoxFor(m => m.Adi, null, new { @class = "form-control", @readonly = true })
                        }
                    </div>
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("BolgeKodu", ViewData.ModelState)">
                        <label>Bölge Kodu </label>
                        @Html.DropDownListFor(m => m.BolgeKodu, bolgeKodlari, Resources.BolgeKoduSelectInfoMsg, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.BolgeKodu, "", new { @class = "help-block" })
                    </div>
                </div>
                <div class="box-footer">
                    <a href="Liste" class="btn btn-danger">İptal</a>
                    <button type="submit" class="btn btn-primary pull-right">Kaydet</button>
                </div>
            </div>
        </div>
    </div>
}

Gov.GTB.FirmaTalepTakip.Web/Views/Firma/Liste.cshtml
@using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete
@model IEnumerable<Gov.GTB.FirmaTalepTakip.Model.Entities.Firma>
@{
    ViewBag.Title = "Firma Bilgileri";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-default">
            <div class="box-header">
                @using (Html.BeginForm("Ara", "Firma", FormMethod.Get))
                {
                    <div class="input-group @FirmaHtmlHelper.ValidationClass("vergiNo", ViewData.ModelState)" style="width: 300px">
                        <input type="number" name="vergiNo" class="form-control" placeholder="Vergi No Giriniz...">

                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                }
                @Html.ValidationMessage("vergiNo", "", new { @class = "text-danger" })
                <div class="pull-right box-tools">
                    @Html.ActionLink("Firma Ekle", "Ekle", null, new { @class = "btn btn-success" })
                </div>
            </div>
            <div class="box-body">
                <table id="tableFirmaListesi" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>SIRA NO</th>
                            <th>VERGİ NO</th>
                            <th>ADI</th>
                            <th>BÖLGE KODU</th>
                            <th style="width:10%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.FirmaId</td>
                                <td>@item.VergiNo</td>
                                <td>@item.Adi</td>
                                <td>@item.BolgeKod.Adi</td>
                                <td>
                                    @Html.ActionLink("Güncelle", "Duzenle", new { item.FirmaId }, new { @class = "btn btn-primary btn-xs" })
                                    @Html.ActionLink("Sil", "Sil", new { item.FirmaId }, new { @class = "btn btn-danger btn-xs" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>