Gov.GTB.FirmaTalepTakip.Web/Controllers/GorevlendirmeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Gov.GTB.FirmaTalepTakip.Model.Entities;
using Gov.GTB.FirmaTalepTakip.Model.ViewModel;
using Gov.GTB.FirmaTalepTakip.Repository.Interface;
using Gov.GTB.FirmaTalepTakip.Web.Helpers;
using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete;

namespace Gov.GTB.FirmaTalepTakip.Web.Controllers
{
    [Authorize]
    [SessionExpireFilter]
    public class GorevlendirmeController : Controller
    {
        private readonly IFirmaRepository _firmaRepository;
        private readonly IUserRepository _userRepository;

        public GorevlendirmeController(IFirmaRepository firmaRepository, IUserRepository userRepository)
        {
            _firmaRepository = firmaRepository;
            _userRepository = userRepository;
        }

        public ActionResult Liste()
        {
            var firmaViewModel = FirmaPersonelListesiGetir();
            return View(firmaViewModel);
        }

        private IEnumerable<FirmaViewModel> FirmaPersonelListesiGetir()
        {
            var firmalar = _firmaRepository.FirmaListesi();
            var firmaViewModel = Mapper.Map<IEnumerable<Firma>, IEnumerable<FirmaViewModel>>(firmalar);
            var siraNo = 1;
            foreach (var model in firmaViewModel)
            {
                model.SiraNo = siraNo++;
            }
            return firmaViewModel;
        }

        public ActionResult Ara(string vergiNo)
        {
            var firmaViewModel = FirmaPersonelListesiGetir();

            if (string.IsNullOrEmpty(vergiNo))
            {
                ModelState.AddModelError("vergiNo", Resources.VergiNoEmptyErrorMsg);
                return View("Liste", firmaViewModel);
            }

            long vergiNoParam = 0;
            if (!long.TryParse(vergiNo, out vergiNoParam))
            {
                ModelState.AddModelError("vergiNo", Resources.VergiNoFormatErrorMsg);
                return View("Liste", firmaViewModel);
            }

            var filteredFirmalar = firmaViewModel.Where(z => z.VergiNo == vergiNoParam.ToString());
            return View("Liste", filteredFirmalar);
        }

        public ActionResult Ekle()
        {
            var currentGumrukKullanici = (GumrukKullanici)Session["CurrentGumrukKullanici"];
            var gorevlendirmeViewModel = new GorevlendirmeViewModel
            {
                GorevlendirmeFirmaListesi = _firmaRepository.GorevlendirilecekFirmalariGetir(currentGumrukKullanici.BolgeKodu),
                GorevlendirmKullaniciListesi = _userRepository.GorevlendirilecekKullanicilariGetir(currentGumrukKullanici.BolgeKodu)
            };
            return View("Duzenle", gorevlendirmeViewModel);
        }

        public ActionResult Duzenle(int id)
        {
            var gorevlendirmeViewModel = GorevlendirmeViewModelGetir(id);
            return View(gorevlendirmeViewModel);
        }

        private GorevlendirmeViewModel GorevlendirmeViewModelGetir(int id)
        {
            var firmaFromDb = _firmaRepository.FirmaGetir(id);
            var currentGumrukKullanici = (GumrukKullanici)Session["CurrentGumrukKullanici"];
            var gorevlendirmeViewModel = new GorevlendirmeViewModel
            {
                FirmaId = firmaFromDb.FirmaId,
                VergiNo = firmaFromDb.VergiNo.ToString(),
                GumrukKullaniciId = firmaFromDb.GumrukKullaniciId ?? 0,
                GorevlendirmeFirmaListesi = new List<GorevlendirmeFirmaViewModel>
                {
                    new GorevlendirmeFirmaViewModel
                    {
                        FirmaId = firmaFromDb.FirmaId,
                        FirmaAdi = firmaFromDb.Adi
                    }
                },
                GorevlendirmKullaniciListesi = _userRepository.GorevlendirilecekKullanicilariGetir(currentGumrukKullanici.BolgeKodu)
            };
            return gorevlendirmeViewModel;
        }

        [HttpPost]
        public ActionResult Duzenle(GorevlendirmeViewModel gorevlendirmeViewModel)
        {
            if (ModelState.IsValid)
            {
                _firmaRepository.FirmaPersonelGorevlendir(gorevlendirmeViewModel.FirmaId, gorevlendirmeViewModel.GumrukKullaniciId);
                return RedirectToAction("Liste");
            }
            else
            {
                if (gorevlendirmeViewModel.FirmaId == 0)
                {
                    var currentGumrukKullanici = (GumrukKullanici)Session["CurrentGumrukKullanici"];
                    gorevlendirmeViewModel.GorevlendirmeFirmaListesi = _firmaRepository.GorevlendirilecekFirmalariGetir(currentGumrukKullanici.BolgeKodu);
                    gorevlendirmeViewModel.GorevlendirmKullaniciListesi = _userRepository.GorevlendirilecekKullanicilariGetir(currentGumrukKullanici.BolgeKodu);
                }
                else
                {
                    gorevlendirmeViewModel = GorevlendirmeViewModelGetir(gorevlendirmeViewModel.FirmaId);
                }

                return View(gorevlendirmeViewModel);
            }
        }

        public ActionResult Sil(int id)
        {
            _firmaRepository.FirmaPersonelGorevlendir(id, null);
            return RedirectToAction("Liste");
        }
    }
}

Gov.GTB.FirmaTalepTakip.Web/Views/Gorevlendirme/Duzenle.cshtml
@using Gov.GTB.FirmaTalepTakip.Web.Helpers
@using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete;
@model Gov.GTB.FirmaTalepTakip.Model.ViewModel.GorevlendirmeViewModel
@{
    ViewBag.Title = "Personel Görevlendir - " + ((@Model.GumrukKullaniciId != 0) ? "Güncelle" : "Yeni Kayıt");
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

@{
    var firmaListesi = new List<SelectListItem> { };
    if (Model.GorevlendirmeFirmaListesi != null)
    {
        Model.GorevlendirmeFirmaListesi.ToList().ForEach(g => firmaListesi.Add(
            new SelectListItem()
            {
                Text = g.FirmaAdi,
                Value = g.FirmaId.ToString()
            }));
    }

    var personelListesi = new List<SelectListItem> { };
    if (Model.GorevlendirmKullaniciListesi != null)
    {
        Model.GorevlendirmKullaniciListesi.ToList().ForEach(g => personelListesi.Add(
            new SelectListItem()
            {
                Text = g.KullaniciAdi,
                Value = g.KullaniciId.ToString()
            }));
    }

    var url = Model.FirmaId != 0 ? "../Liste" : "Liste";
}

<script type="text/javascript">
    $(function () {
        $("#FirmaId").change(function () {
            var firmaId = $(this).val();
            if (firmaId === '') {
                $('#VergiNo').val('');
            }
            else {
                $.ajax({
                    type: "GET",
                    url: '/Account/FirmaVergiNoGetir?firmaId=' + firmaId,
                    success: function (result) {
                        console.log(result);
                        $('#VergiNo').val(result);
                    }
                });
            }
        });
    });

</script>

@using (Html.BeginForm("Duzenle", "Gorevlendirme", FormMethod.Post))
{
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-body">
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("FirmaId", ViewData.ModelState)">
                        <label>Firma Adı </label>
                        @Html.DropDownListFor(m => m.FirmaId, firmaListesi, Resources.FirmaSelectInfoMsg, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.FirmaId, "", new { @class = "help-block" })
                    </div>
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("VergiNo", ViewData.ModelState)">
                        <label>Firma Vergi No </label>
                        @Html.TextBoxFor(m => m.VergiNo, null, new { @class = "form-control", @readonly = true })
                        @Html.ValidationMessageFor(m => m.VergiNo, "", new { @class = "help-block" })
                    </div>
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("GumrukKullaniciId", ViewData.ModelState)">
                        <label>Personel </label>
                        @Html.DropDownListFor(m => m.GumrukKullaniciId, personelListesi, Resources.PersonelSelectInfoMsg, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.GumrukKullaniciId, "", new { @class = "help-block" })
                    </div>
                </div>
                <div class="box-footer">
                    <a href=@url class="btn btn-danger">İptal</a>
                    <button type="submit" class="btn btn-primary pull-right">Kaydet</button>
                </div>
            </div>
        </div>
    </div>
}

Gov.GTB.FirmaTalepTakip.Web/Views/Gorevlendirme/Liste.cshtml
@using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete
@model IEnumerable<Gov.GTB.FirmaTalepTakip.Model.ViewModel.FirmaViewModel>
@{
    ViewBag.Title = "Personel Görevlendirme Listesi";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-default">
            <div class="box-header">
                @using (Html.BeginForm("Ara", "Gorevlendirme", FormMethod.Get))
                {
                    <div class="input-group @FirmaHtmlHelper.ValidationClass("vergiNo", ViewData.ModelState)" style="width: 300px">
                        <input type="number" name="vergiNo" class="form-control" placeholder="Vergi No Giriniz...">

                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                }
                @Html.ValidationMessage("vergiNo", "", new { @class = "text-danger" })
                <div class="pull-right box-tools">
                    @Html.ActionLink("Yeni Personel Görevlendir", "Ekle", null, new { @class = "btn btn-success" })
                </div>
            </div>
            <div class="box-body">
                <table id="tableFirmaListesi" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>SIRA NO</th>
                            <th>VERGİ NO</th>
                            <th>ADI</th>
                            <th>PERSONEL</th>
                            <th style="width:10%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.SiraNo</td>
                                <td>@item.VergiNo</td>
                                <td>@item.Adi</td>
                                <td>@item.GumrukKullaniciAdSoyad</td>
                                <td>
                                    @Html.ActionLink("Güncelle", "Duzenle", new { item.Id }, new { @class = "btn btn-primary btn-xs" })
                                    @Html.ActionLink("Sil", "Sil", new { item.Id }, new { @class = "btn btn-danger btn-xs" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>