Gov.GTB.FirmaTalepTakip.Web/Controllers/TalepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Gov.GTB.FirmaTalepTakip.Model.Entities;
using Gov.GTB.FirmaTalepTakip.Model.Enums;
using Gov.GTB.FirmaTalepTakip.Model.ViewModel;
using Gov.GTB.FirmaTalepTakip.Repository.Interface;
using Gov.GTB.FirmaTalepTakip.Repository.Repository;
using Gov.GTB.FirmaTalepTakip.Web.Helpers;
using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete;

namespace Gov.GTB.FirmaTalepTakip.Web.Controllers
{
    [Authorize]
    [SessionExpireFilter]
    public class TalepController : Controller
    {
        private readonly ITalepDetayFirmaRepository _talepDetayFirmaRepository;
        private readonly IRefTalepKonuRepository _refTalepKonuRepository;
        public readonly ICevapRepository _cevapRepository;
        private readonly IRefTalepCevapRepository _refTalepCevapRepository;
        private readonly IUserRepository _userRepository;

        public TalepController(ITalepDetayFirmaRepository talepDetayFirmaRepository,
            IRefTalepKonuRepository refTalepKonuRepository, ICevapRepository cevapRepository,
            IRefTalepCevapRepository refTalepCevapRepository, IUserRepository userRepository)
        {
            _talepDetayFirmaRepository = talepDetayFirmaRepository;
            _refTalepKonuRepository = refTalepKonuRepository;
            _cevapRepository = cevapRepository;
            _refTalepCevapRepository = refTalepCevapRepository;
            _userRepository = userRepository;
        }

        public ActionResult Liste()
        {
            var talepler = TalepleriGetir();
            SiraNoAyarla(talepler);

            return View(talepler);
        }

        private static void SiraNoAyarla(IEnumerable<TalepDetayFirmaViewModel> talepler)
        {
            var siraNo = 1;
            foreach (var talepDetayFirmaViewModel in talepler)
            {
                talepDetayFirmaViewModel.SiraNo = siraNo++;
            }
        }

        private IEnumerable<TalepDetayFirmaViewModel> TalepleriGetir()
        {
            var currentUserTcNo = (long)Session["CurrentUserTcNo"];
            var kullaniciYetkileri = (KullaniciYetkileri)Session["CurrentUser_Auths"];
            string bolgeKodu = null;
            if (kullaniciYetkileri.KullaniciRolEnum != RolEnum.FIP)
            {
                var bipGumrukKullanici = (GumrukKullanici)Session["CurrentGumrukKullanici"];
                bolgeKodu = bipGumrukKullanici.BolgeKodu;
            }

            return _talepDetayFirmaRepository.TalepListesi(currentUserTcNo, bolgeKodu);
        }

        public ActionResult Ekle()
        {
            var talepViewModel = new TalepDetayFirmaViewModel()
            {
                Konular = _refTalepKonuRepository.TalepKonuListesi()
            };
            return View("Duzenle", talepViewModel);
        }

        public ActionResult Duzenle(int id)
        {
            var talepFromDb = _talepDetayFirmaRepository.TalepDetayGetir(id);
            var talepViewModel = Mapper.Map<TalepDetayFirma, TalepDetayFirmaViewModel>(talepFromDb);
            talepViewModel.Konular = _refTalepKonuRepository.TalepKonuListesi();
            return View(talepViewModel);
        }

        public ActionResult Ara(string aramaKriteri, string aramaKriterDegeri)
        {
            var talepViewModel = TalepleriGetir();
            SiraNoAyarla(talepViewModel);

            if (string.IsNullOrEmpty(aramaKriterDegeri))
            {
                ModelState.AddModelError("aramaKriterDegeri", GetModelEmptyErrorMessage(aramaKriteri));
                return View("Liste", talepViewModel);
            }

            if (aramaKriteri == ((int)AramaKriterEnum.BolgeIrtibatPersoneli).ToString())
            {
                var filteredTalepler = talepViewModel.Where(z => z.IrtibatPersoneli.Contains(aramaKriterDegeri));
                return View("Liste", filteredTalepler);
            }
            else
            {
                long aramaKriterDegeriParam = 0;
                if (!long.TryParse(aramaKriterDegeri, out aramaKriterDegeriParam))
                {
                    ModelState.AddModelError("aramaKriterDegeri", GetModelFormatErrorMessage(aramaKriteri));
                    return View("Liste", talepViewModel);
                }

                IEnumerable<TalepDetayFirmaViewModel> filteredTalepler = new List<TalepDetayFirmaViewModel>();
                if (aramaKriteri == ((int)AramaKriterEnum.TalepReferansNo).ToString())
                    filteredTalepler = talepViewModel.Where(z => z.TalepReferansNo == aramaKriterDegeriParam);
                else if (aramaKriteri == ((int)AramaKriterEnum.FirmaVergiNo).ToString())
                    filteredTalepler = talepViewModel.Where(z => z.VergiNo == aramaKriterDegeriParam);

                return View("Liste", filteredTalepler);
            }
        }

        public string GetModelEmptyErrorMessage(string aramaKriteri)
        {
            if (aramaKriteri == ((int)AramaKriterEnum.FirmaVergiNo).ToString())
                return Resources.FirmaVergiNoEmptyErrorMsg;

            if (aramaKriteri == ((int)AramaKriterEnum.TalepReferansNo).ToString())
                return Resources.TalepReferansNoEmptyErrorMsg;

            if (aramaKriteri == ((int)AramaKriterEnum.BolgeIrtibatPersoneli).ToString())
                return Resources.BolgeIrtibatPersoneliEmptyErrorMsg;

            return string.Empty;
        }

        public string GetModelFormatErrorMessage(string aramaKriteri)
        {
            if (aramaKriteri == ((int)AramaKriterEnum.FirmaVergiNo).ToString())
                return Resources.FirmaVergiNoFormatErrorMsg;

            if (aramaKriteri == ((int)AramaKriterEnum.TalepReferansNo).ToString())
                return Resources.TalepReferansNoFormatErrorMsg;

            return string.Empty;
        }

        [HttpPost]
        public ActionResult Duzenle(TalepDetayFirmaViewModel talepDetayFirmaViewModel)
        {
            if (ModelState.IsValid)
            {
                var talep = Mapper.Map<TalepDetayFirmaViewModel, TalepDetayFirma>(talepDetayFirmaViewModel);
                var firmaKullanici = (FirmaKullanici)Session["CurrentFirmaKullanici"];
                talep.VergiNo = firmaKullanici.VergiNo;
                talep.FirmaKullaniciId = firmaKullanici.Id;
                talep.TalepTarih = DateTime.Now;
                talep.CevapDurum = false;
                _talepDetayFirmaRepository.TalepKaydetGuncelle(talep);
                return RedirectToAction("Liste");
            }
            else
            {
                var talepViewModel = new TalepDetayFirmaViewModel()
                {
                    Konular = _refTalepKonuRepository.TalepKonuListesi()
                };
                return View("Duzenle", talepViewModel);
            }
        }

        public ActionResult Cevap(long id)
        {
            var cevapTalep = _cevapRepository.TalepCevabiGetir(id);
            var cevapViewModel = Mapper.Map<CevapDetayGumruk, CevapViewModel>(cevapTalep);
            var talep = _talepDetayFirmaRepository.TalepDetayGetir(id);
            cevapViewModel.TalepReferansNo = talep.TalepReferansNo;
            return View(cevapViewModel);
        }

        public ActionResult Cevapla(long id)
        {
            var talepFromDb = _talepDetayFirmaRepository.TalepDetayGetir(id);
            var cevap = _cevapRepository.TalepCevabiGetir(id);

            var cevapViewModel = new CevapViewModel
            {
                TalepReferansNo = talepFromDb.TalepReferansNo,
                TalepKonu = talepFromDb.RefTalepKonu.TKonu,
                TalepAciklama = talepFromDb.KonuTalepAciklama,
                CevapBasliklar = _refTalepCevapRepository.TalepCevapListesi(),
                CevapDetayGumrukId = talepFromDb.CevapDetayGumrukId,
                TcNoIrtibatPersoneli = Session["CurrentUserTcNo"].ToString(),
                CevapAciklama = cevap.CevapAciklama,
                RefTalepCevapId = cevap.RefTalepCevapId
            };

            return View("Cevapla", cevapViewModel);
        }

        [HttpPost]
        public ActionResult Cevapla(CevapViewModel cevapViewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _talepDetayFirmaRepository.TalepCevapla(cevapViewModel);
                if (result)
                    return RedirectToAction("Liste");
            }
            return RedirectToCevapla();
        }

        private ActionResult RedirectToCevapla()
        {
            var talepCevapViewModel = new CevapViewModel
            {
                CevapBasliklar = _refTalepCevapRepository.TalepCevapListesi()
            };
            return View("Cevapla", talepCevapViewModel);
        }

        public ActionResult Goruntule(int id)
        {
            var talepFromDb = _talepDetayFirmaRepository.TalepDetayGetir(id);
            var talepViewModel = Mapper.Map<TalepDetayFirma, TalepDetayFirmaViewModel>(talepFromDb);
            if (talepViewModel.CevapDetayGumruk != null)
            {
                var kullanici = _userRepository.KullaniciGetirTcNoIle(talepViewModel.CevapDetayGumruk.TcNoIrtibatPersoneli);
                if (kullanici != null)
                {
                    talepViewModel.CevaplayanPersonel = kullanici.Adi + " " + kullanici.Soyadi;
                }
            }
            return View(talepViewModel);
        }
    }
}

Gov.GTB.FirmaTalepTakip.Web/Views/Talep/Cevap.cshtml
@model Gov.GTB.FirmaTalepTakip.Model.ViewModel.CevapViewModel
@{
    ViewBag.Title = "Talep Cevabı";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-default">
            <div class="box-body">
                <div class="form-group">
                    <label>Talep Referans No </label>
                    @Html.TextBoxFor(m => m.TalepReferansNo, null, new { @class = "form-control", @readonly = true })
                </div>
                <div class="form-group">
                    <label>Cevap Başlık </label>
                    @Html.TextBoxFor(m => m.RefTalepCevap.CKonu, null, new { @class = "form-control", @readonly = true })
                </div>
                <div class="form-group">
                    <label>Cevap Açıklama </label>
                    @Html.TextAreaFor(m => m.CevapAciklama, 5, 20, new { @class = "form-control", @readonly = true })
                </div>
                <div class="form-group">
                    <label>Cevaplanma Tarihi </label>
                    @Html.TextBoxFor(m => m.CevapTarih, null, new { @class = "form-control", @readonly = true })
                </div>
                <div class="box-footer text-center">
                    <a href="../Liste" class="btn btn-primary"><< Talep Listesine Geri Dön</a>
                </div>
            </div>
        </div>
    </div>
</div>

Gov.GTB.FirmaTalepTakip.Web/Views/Talep/Cevapla.cshtml
@using Gov.GTB.FirmaTalepTakip.Web.Helpers
@using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete
@model Gov.GTB.FirmaTalepTakip.Model.ViewModel.CevapViewModel
@{
    ViewBag.Title = "Cevapla";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

@{
    var cevapListesi = new List<SelectListItem>();
    if (Model.CevapBasliklar != null)
    {
        Model.CevapBasliklar.ToList().ForEach(g => cevapListesi.Add(
            new SelectListItem()
            {
                Text = g.CKonu,
                Value = g.Id.ToString()
            }));
    }
}


@using (Html.BeginForm("Cevapla", "Talep", FormMethod.Post))
{
    @Html.HiddenFor(model => model.CevapDetayGumrukId)
    @Html.HiddenFor(model => model.TcNoIrtibatPersoneli)
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-body">
                    <div class="form-group">
                        <label>Talep Referans No </label>
                        @Html.TextBoxFor(m => m.TalepReferansNo, null, new { @class = "form-control", @readonly = true })
                    </div>
                    <div class="form-group">
                        <label>Talep Konusu </label>
                        @Html.TextBoxFor(m => m.TalepKonu, null, new { @class = "form-control", @readonly = true })
                    </div>
                    <div class="form-group">
                        <label>Talep Açıklama </label>
                        @Html.TextAreaFor(m => m.TalepAciklama, 5, 20, new { @class = "form-control", @readonly = true })
                    </div>
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("RefTalepCevapId", ViewData.ModelState)">
                        <label>Cevap Konusu</label>
                        @Html.DropDownListFor(m => m.RefTalepCevapId, cevapListesi, Resources.SelectInfoMsg, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.RefTalepCevapId, "", new { @class = "help-block" })
                    </div>
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("CevapAciklama", ViewData.ModelState)">
                        <label>Cevap Açıklama </label>
                        @Html.TextAreaFor(m => m.CevapAciklama, 5, 20, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CevapAciklama, "", new { @class = "help-block" })
                    </div>
                    <div class="box-footer">
                        <a href="../Liste" class="btn btn-danger">İptal</a>
                        <button type="submit" class="btn btn-primary pull-right">@(Model.CevapDetayGumrukId.HasValue ? Html.Raw("Talebi Güncelle") : Html.Raw("Talebi Cevapla"))</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Gov.GTB.FirmaTalepTakip.Web/Views/Talep/Duzenle.cshtml
@using Gov.GTB.FirmaTalepTakip.Web.Helpers
@using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete
@model Gov.GTB.FirmaTalepTakip.Model.ViewModel.TalepDetayFirmaViewModel
@{
    ViewBag.Title = (Model.Id > 0) ? "Talep Bilgileri" : "Yeni Talep";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

@{
    var konuListesi = new List<SelectListItem>();
    if (Model.Konular != null)
    {
        Model.Konular.ToList().ForEach(g => konuListesi.Add(
            new SelectListItem()
            {
                Text = g.TKonu,
                Value = g.Id.ToString()
            }));
    }
}


@using (Html.BeginForm("Duzenle", "Talep", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.TalepReferansNo)
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-body">
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("RefTalepKonuId", ViewData.ModelState)">
                        <label>Talep Konusu</label>
                        @Html.DropDownListFor(m => m.RefTalepKonuId, konuListesi, Resources.SelectInfoMsg, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.RefTalepKonuId, "", new { @class = "help-block" })
                    </div>
                    <div class="form-group @FirmaHtmlHelper.ValidationClass("KonuTalepAciklama", ViewData.ModelState)">
                        <label>Açıklama</label>
                        @Html.TextAreaFor(m => m.KonuTalepAciklama, 5, 20, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.KonuTalepAciklama, "", new { @class = "help-block" })
                    </div>
                    <div class="box-footer text-center">
                        <button type="submit" class="btn btn-primary">Talebi Kaydet</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Gov.GTB.FirmaTalepTakip.Web/Views/Talep/Goruntule.cshtml
@model Gov.GTB.FirmaTalepTakip.Model.ViewModel.TalepDetayFirmaViewModel
@{
    ViewBag.Title = "Talep Bilgileri";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-default">
            <form class="form-horizontal">
                <div class="box-body">
                    <div class="form-group">
                        <label for="TalepReferansNo" class="col-sm-2 control-label">Talep Referans No</label>
                        <div class="col-sm-10">
                            <label class="form-control" style="font-weight:normal">@Model.TalepReferansNo</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="RefTalepKonu" class="col-sm-2 control-label">Talep Konusu</label>
                        <div class="col-sm-10">
                            <label class="form-control" style="font-weight:normal">@Model.RefTalepKonu.TKonu</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="KonuTalepAciklama" class="col-sm-2 control-label">Talep Açıklama</label>
                        <div class="col-sm-10">
                            <label class="form-control" style="font-weight:normal">@Model.KonuTalepAciklama</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="IrtibatPersoneli" class="col-sm-2 control-label">Firma İrtibat Personeli</label>
                        <div class="col-sm-10">
                            <label class="form-control" style="font-weight:normal">@Model.IrtibatPersoneli</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="TalepTarih" class="col-sm-2 control-label">Talep Tarihi</label>
                        <div class="col-sm-10">
                            <label class="form-control" style="font-weight:normal">@Model.TalepTarih.Value</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="CevapDurum" class="col-sm-2 control-label">Cevap Durumu</label>
                        <div class="col-sm-10">
                            <label class="form-control" style="font-weight:normal">@(Model.CevapDurum ? Html.Raw("CEVAPLANDI") : Html.Raw("CEVAPLANMADI"))</label>
                        </div>
                    </div>
                    @if (Model.CevapDurum)
                    {
                        <div class="form-group">
                            <label for="CKonu" class="col-sm-2 control-label">Cevap Konusu</label>
                            <div class="col-sm-10">
                                <label class="form-control" style="font-weight:normal">@Model.CevapDetayGumruk.RefTalepCevap.CKonu</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="CevapAciklama" class="col-sm-2 control-label">Cevap Açıklama</label>
                            <div class="col-sm-10">
                                <label class="form-control" style="font-weight:normal">@Model.CevapDetayGumruk.CevapAciklama</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="CevapTarih" class="col-sm-2 control-label">Cevaplanma Tarihi</label>
                            <div class="col-sm-10">
                                <label class="form-control" style="font-weight:normal">@(Model.CevapDetayGumruk.CevapTarih.HasValue ? Html.Raw(Model.CevapDetayGumruk.CevapTarih.Value.ToLongDateString()) : Html.Raw(""))</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="CevapAciklama" class="col-sm-2 control-label">Cevaplayan Personel</label>
                            <div class="col-sm-10">
                                <label class="form-control" style="font-weight:normal">@Model.CevaplayanPersonel</label>
                            </div>
                        </div>
                    }
                </div>
            </form>
        </div>
    </div>
</div>

Gov.GTB.FirmaTalepTakip.Web/Views/Talep/Liste.cshtml
@using Gov.GTB.FirmaTalepTakip.Model.Enums
@using Gov.GTB.FirmaTalepTakip.Model.ViewModel
@using Gov.GTB.FirmaTalepTakip.Web.Helpers
@using Gov.GTB.FirmaTalepTakip.Web.Infrastructure.Concrete
@model IEnumerable<Gov.GTB.FirmaTalepTakip.Model.ViewModel.TalepDetayFirmaViewModel>
@{
    ViewBag.Title = "Talep Listesi";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

@{
    var kullaniciRol = (KullaniciYetkileri)Session["CurrentUser_Auths"];
    var aramaKriterListesi = new List<SelectListItem>
{
new SelectListItem {Value = "1", Text = Resources.FirmaVergiNo},
new SelectListItem {Value = "2", Text = Resources.TalepReferansNo},
new SelectListItem {Value = "3", Text = Resources.BolgeIrtibatPersoneli}
};
}

<script type="text/javascript">
    $(function () {
        SetPlaceholder();
        $("#aramaKriteri").change(function () {
            SetPlaceholder();
        });
    });

    function SetPlaceholder() {
        var aramaKriteriId = $("#aramaKriteri").val();
        var aramaDegeri = $("#aramaKriterDegeri");
        if (aramaKriteriId === "1") {
            aramaDegeri.attr("placeholder", "Firma Vergi No Giriniz");
        }
        else if (aramaKriteriId === "2") {
            aramaDegeri.attr("placeholder", "Talep Referans No Giriniz");
        }
        else if (aramaKriteriId === "3") {
            aramaDegeri.attr("placeholder", "Bölge İrtibat Personeli Giriniz");
        }
    }

</script>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-default">
            <div class="box-header">
                @using (Html.BeginForm("Ara", "Talep", FormMethod.Get))
                {
                    <div style="width: 480px">
                        <table class="table table-responsive table-condensed table-striped">
                            <tr>
                                <td>
                                    @Html.DropDownList("aramaKriteri", aramaKriterListesi, new { @class = "form-control" })
                                </td>
                                <td>
                                    <div class="@FirmaHtmlHelper.ValidationClass("aramaKriterDegeri", ViewData.ModelState)">
                                        <input type="text" id="aramaKriterDegeri" name="aramaKriterDegeri" class="form-control" placeholder="Firma Vergi No Giriniz...">
                                    </div>
                                </td>
                                <td>
                                    <span class="input-group-btn">
                                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </td>
                            </tr>
                        </table>
                    </div>
                }
                @Html.ValidationMessage("aramaKriterDegeri", "", new { @class = "text-danger" })
            </div>
            <div class="box-body">
                <table id="tableFirmaListesi" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>SIRA NO</th>
                            <th>TALEP REFERANS NO</th>
                            @if (kullaniciRol.KullaniciRolEnum != RolEnum.FIP)
                            {
                                <th>FİRMA ADI</th>
                                <th>FİRMA İRTİBAT PERSONELİ</th>
                            }
                            <th>TALEP KONUSU</th>
                            <th>TARİH</th>
                            @if (kullaniciRol.KullaniciRolEnum == RolEnum.FIP)
                            {
                                <th>TALEP YAPAN KİŞİ</th>
                            }
                            <th>CEVAPLANMA DURUMU</th>
                            @if (kullaniciRol.KullaniciRolEnum != RolEnum.BM && kullaniciRol.KullaniciRolEnum != RolEnum.GGM)
                            {
                                <th style="width: 15%"></th>
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.SiraNo</td>
                                <td>
                                    @if (kullaniciRol.KullaniciRolEnum == RolEnum.BM || kullaniciRol.KullaniciRolEnum == RolEnum.GGM)
                                    {
                                        <a href="Goruntule/@item.Id">@item.TalepReferansNo</a>
                                    }
                                    else
                                    {
                                        @item.TalepReferansNo
                                    }
                                </td>
                                @if (kullaniciRol.KullaniciRolEnum != RolEnum.FIP)
                                {
                                    <td>@item.FirmaAdi</td>
                                    <td>@item.IrtibatPersoneli</td>
                                }
                                <td>@item.RefTalepKonu.TKonu</td>
                                <td>@item.TalepTarih</td>
                                @if (kullaniciRol.KullaniciRolEnum == RolEnum.FIP)
                                {
                                    <td>@item.FirmaKullanici.Adi @item.FirmaKullanici.Soyadi</td>
                                }
                                <td>@(item.CevapDurum ? Html.Raw("CEVAPLANDI") : Html.Raw("CEVAPLANMADI"))</td>
                                @if (kullaniciRol.KullaniciRolEnum != RolEnum.BM && kullaniciRol.KullaniciRolEnum != RolEnum.GGM)
                                {
                                    <td>
                                        @if (item.CevapDurum != true)
                                        {
                                            if (kullaniciRol.KullaniciRolEnum == RolEnum.FIP)
                                            {
                                                @Html.ActionLink("Güncelle", "Duzenle", new { item.Id }, new { @class = "btn btn-primary btn-xs" })
                                            }
                                            else if (kullaniciRol.KullaniciRolEnum == RolEnum.BIP)
                                            {
                                                @Html.ActionLink("Cevapla", "Cevapla", new { item.Id }, new { @class = "btn btn-primary btn-xs" })
                                            }
                                        }
                                        else
                                        {
                                            if (kullaniciRol.KullaniciRolEnum == RolEnum.FIP)
                                            {
                                                @Html.ActionLink("Görüntüle", "Cevap", new { item.Id }, new { @class = "btn btn-info btn-xs" })
                                            }
                                            else if (kullaniciRol.KullaniciRolEnum == RolEnum.BIP)
                                            {
                                                @Html.ActionLink("Güncelle", "Cevapla", new { item.Id }, new { @class = "btn btn-warning btn-xs" })
                                                @Html.ActionLink("Görüntüle", "Cevap", new { item.Id }, new { @class = "btn btn-info btn-xs" })
                                            }
                                        }
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>